bindgen-llhttp:
  k1bindgen -i libs/llhttp.h -o llhttp.k1 -n llhttp \
    -clangarg -isysroot \
    -clangarg "$(xcrun --sdk macosx --show-sdk-path)" \
    -exclude llhttp__internal_init \
    -exclude llhttp__internal_execute

bindgen-libuv:
  k1bindgen -i libs/libuv/include/uv.h -o uv.k1 -n uv \
    -clangarg -Ilibs/libuv/include \
    -system false \
    -clangarg -isysroot \
    -clangarg "$(xcrun --sdk macosx --show-sdk-path)" \

build-llhttp:
  git submodule update llhttp
  cd llhttp && \
    npm ci && \
    make
  cp llhttp/build/libllhttp.a libs/
  cp llhttp/build/libllhttp.so libs/
  cp llhttp/build/llhttp.h libs/
