build:
  k1 b .

run:
  k1 r .

bindgen: bindgen-llhttp bindgen-net bindgen-libuv

bindgen-llhttp:
  k1bindgen -i libs/llhttp.h -o llhttp.k1 -n llhttp \
    -clangarg -isysroot \
    -clangarg "$(xcrun --sdk macosx --show-sdk-path)" \
    -exclude llhttp__internal_init \
    -exclude llhttp__internal_execute

bindgen-net:
  k1bindgen -i net.c -o net.k1 -n net \
    -clangarg -isysroot \
    -clangarg "$(xcrun --sdk macosx --show-sdk-path)" \
    -system true \
    -include sockaddr_in \
    -include sockaddr_in6 \
    -include sa_family_t \
    -include sockaddr \
    -include socklen_t \
    -opaque socklen_t \
    -include addrinfo \
    -include in_port_t \
    -include in_addr \
    -include in6_addr \
    -include in_addr_t \
    -include FILE \
    -opaque FILE

bindgen-libuv:
  k1bindgen -i libs/libuv/include/uv.h -o uv.k1 -n uv \
    -clangarg -Ilibs/libuv/include \
    -system false \
    -clangarg -isysroot \
    -clangarg "$(xcrun --sdk macosx --show-sdk-path)" \
    -prelude-file uv_bindgen_prelude.k1.txt \
    -opaque uv__dirent_t \
    -opaque uv_uid_t \
    -opaque uv_gid_t \
    -opaque uv_pid_t \
    -opaque uv_once_t \
    -opaque uv_thread_t \
    -opaque uv_mutex_t \
    -opaque uv_rwlock_t \
    -opaque uv_sem_t \
    -opaque uv_cond_t \
    -opaque uv_key_t \
    -opaque _uv_barrier \
    -opaque uv_loop_s \
    -opaque uv_loop_t \
    -opaque uv_connect_t \
    -opaque uv_connect_s \
    -opaque uv_shutdown_s \
    -opaque uv_shutdown_t \
    -opaque uv_handle_t \
    -opaque uv_handle_s \
    -opaque uv_fs_event_s \
    -opaque uv_fs_event_t \
    -opaque uv_fs_poll_s \
    -opaque uv_fs_poll_t \
    -opaque uv_any_handle \
    -opaque uv_any_req \
    -opaque uv_stream_s \
    -opaque uv_stream_t \
    -opaque uv_tcp_t \
    -opaque uv_tcp_s \
    -opaque uv_udp_t \
    -opaque uv_udp_s \
    -opaque uv_udp_send_s \
    -opaque uv_udp_send_t \
    -opaque uv_work_s \
    -opaque uv_work_t \
    -opaque uv_pipe_s \
    -opaque uv_pipe_t \
    -opaque uv_tty_t \
    -opaque uv_tty_s \
    -opaque uv_fs_s \
    -opaque uv_fs_t \
    -opaque uv_req_s \
    -opaque uv_req_t \
    -opaque uv_random_t \
    -opaque uv_random_s \
    -opaque uv_poll_s \
    -opaque uv_poll_t \
    -opaque uv_dir_s \
    -opaque uv_dir_t \
    -opaque uv_getaddrinfo_s \
    -opaque uv_getaddrinfo_t \
    -opaque uv_getnameinfo_s \
    -opaque uv_getnameinfo_t \
    -opaque uv_timer_s \
    -opaque uv_timer_t \
    -opaque uv_prepare_s \
    -opaque uv_prepare_t \
    -opaque uv_check_s \
    -opaque uv_check_t \
    -opaque uv_idle_s \
    -opaque uv_idle_t \
    -opaque uv_async_s \
    -opaque uv_async_t \
    -opaque uv_process_s \
    -opaque uv_process_t \
    -opaque uv_fs_event_t \
    -opaque uv_fs_poll_t \
    -opaque uv_signal_t \
    -opaque uv_signal_s \
    -exclude uv__queue \
    -exclude uv__work \
    -exclude uv__io_t \
    -exclude uv__io_s \
    -opaque uv_write_s \
    -opaque uv_write_t \
    -exclude UV_OVERLAPPED_PIPE

build-llhttp:
  git submodule update llhttp
  cd llhttp && \
    npm ci && \
    make
  cp llhttp/build/libllhttp.a libs/
  cp llhttp/build/libllhttp.so libs/
  cp llhttp/build/llhttp.h libs/
