#!/bin/bash
# Show output and commands
set -x
# Exit on errors
set -e
export RUST_BACKTRACE=1
filename=$(basename $1 .k1)
RUST_LOG=debug cargo run -- --debug --no-llvm-opt $1; lldb .k1-out/$filename.out
