#!/bin/bash
# Show output and commands
set -x
# Exit on errors
set -e
FILENAME=${@: -1}
filename=$(basename $FILENAME .k1)
export RUST_BACKTRACE=1
RUST_LOG=debug cargo run --features=llvm-sys/prefer-dynamic -- --debug --write-llvm --no-llvm-opt build $@; lldb .k1-out/$filename
