#!/bin/bash
# Show output and commands
set -x
# Exit on errors
set -e
FILENAME=${@: -1}
filename=$(basename $FILENAME .k1)
export RUST_BACKTRACE=1
RUST_LOG=debug cargo run -- --debug --no-llvm-opt $@; lldb .k1-out/$filename.out
