#!/usr/bin/env python3
"""Generates perf/stress100, a large K1 program for compiler profiling.

Usage: python3 perf/gen_stress.py [units]

Each unit is an independent namespace defining generic types, generic
functions, and abilities, then instantiating them at many types. This
stresses the typer's generic specialization, inference, and ability
impl machinery, which is where compile time goes for real programs.
Each unit also carries ordinary control-flow code -- structs, sums,
matches, if/else chains, while loops, local churn -- so the profile
isn't purely generics. suite1 compiles too fast for most changes to be
measurable.
"""

import sys
from pathlib import Path

UNITS = int(sys.argv[1]) if len(sys.argv) > 1 else 300

UNSIGNED = ["u8", "u16", "u32", "u64"]
SCALARS = UNSIGNED + ["bool", "string", "f32", "f64"]


def unit(i: int) -> str:
    impls_sz = "\n".join(
        f"  impl sz for {t} {{ fn sz(self): u64 "
        f"{{ self{'' if t == 'u64' else '.as[u64]'} + {n + 1} }} }}"
        for n, t in enumerate(UNSIGNED)
    )
    impls_enc = "\n".join(
        f"  impl enc[o = u64] for {t} {{ fn enc(self): u64 "
        f"{{ self{'' if t == 'u64' else '.as[u64]'} }} }}"
        for t in UNSIGNED
    )
    def widen(t: str) -> str:
        return "" if t == "u64" else ".as[u64]"

    boxed = "\n".join(
        f"  acc = acc + get(mk({n + 1}: {t})){widen(t)} + total(mk({n + 1}: {t}))"
        for n, t in enumerate(UNSIGNED)
    )
    deep = "\n".join(
        f"  acc = acc + get(get(wrap2({n + 1}: {t}))){widen(t)}"
        for n, t in enumerate(UNSIGNED)
    )
    pairs = []
    for n in range(len(SCALARS)):
        a = SCALARS[n]
        b = SCALARS[(n + 1) % len(SCALARS)]
        pairs.append(
            f"  let p{n} = swap(mk-pair(zero[{a}](), zero[{b}]()))\n"
            f"  acc = acc + measure(p{n}.first) + measure(p{n}.second)"
        )
    pairs = "\n".join(pairs)
    encs = "\n".join(
        f"  acc = acc + encode({n + 1}: {t})" for n, t in enumerate(UNSIGNED)
    )
    return f"""ns u{i} {{
  type bx[t] = {{ value: t, tag: u64 }}
  type duo[a, b] = {{ first: a, second: b }}
  type vec2 = {{ x: u64, y: u64 }}
  type shape = either {{ dot, line(u64), rect(vec2) }}
  type op = either {{ push(u64), pop, reset }}

  fn area(s: shape): u64 {{
    s is {{
      :dot -> 1,
      :line(len) -> len,
      :rect(d) -> d.x * d.y
    }}
  }}

  fn step(state: vec2, o: op): vec2 {{
    o is {{
      :push(n) -> .{{ x = state.x + n, y = state.y + 1 }},
      :pop -> {{
        if state.y > 0 {{
          .{{ x = state.x, y = state.y - 1 }}
        }} else state
      }},
      :reset -> .{{ x = 0, y = 0 }}
    }}
  }}

  fn churn(seed: u64): u64 {{
    let base = seed + {i}
    let low = base % 7
    let high = base / 3
    let start: vec2 = .{{ x = low, y = high }}
    let s: shape = if low > high :rect(start) else if low == 0 :dot else :line(high)
    let a = area(s)
    let cur = start
    cur = step(cur, :push(a))
    cur = step(cur, :push(low))
    cur = step(cur, :pop)
    cur = if cur.x > 100 step(cur, :reset) else cur
    let k = 0: u64
    let sum = 0: u64
    while k < low {{
      sum = sum + k * 2 + cur.x
      k = k + 1
    }}
    let verdict = cur is {{
      .{{ x = 0, y }} -> y,
      .{{ x, y }} if x == y -> x + y,
      .{{ x, y }} -> x * 2 + y
    }}
    if verdict > sum verdict - sum else sum - verdict + a
  }}

  ability sz {{ fn sz(self): u64 }}
  ability enc[o] {{ fn enc(self): o }}

{impls_sz}
  impl[t: sz] sz for bx[t] {{ fn sz(self): u64 {{ self.value.sz() + 1 }} }}
{impls_enc}

  fn mk[t](value: t): bx[t] {{ .{{ value, tag = {i} }} }}
  fn get[t](b: bx[t]): t {{ b.value }}
  fn wrap2[t](value: t): bx[bx[t]] {{ mk(mk(value)) }}
  fn mk-pair[a, b](first: a, second: b): duo[a, b] {{ .{{ first, second }} }}
  fn swap[a, b](p: duo[a, b]): duo[b, a] {{ .{{ first = p.second, second = p.first }} }}
  fn zero[t](): ?t {{ :none }}
  fn measure[t](v: ?t): u64 {{ if v is :some(_) 1 else 0 }}
  fn total[t: sz](v: t): u64 {{ v.sz() }}
  fn encode[t: enc[o = u64]](v: t): u64 {{ v.enc() }}

  fn test(): u64 {{
  let acc = {i}: u64
{boxed}
{deep}
{pairs}
{encs}
  acc = acc + churn(acc)
  acc = acc + churn(acc % 97)
  acc = acc + churn({i} + 3)
  acc
  }}
}}
"""


def main() -> None:
    out_dir = Path(__file__).parent / "stress100"
    out_dir.mkdir(parents=True, exist_ok=True)
    parts = [f"// Generated by perf/gen_stress.py {UNITS} -- do not edit.\n"]
    for i in range(UNITS):
        parts.append(unit(i))
    calls = "\n".join(f"  acc = acc + u{i}/test()" for i in range(UNITS))
    parts.append(f"fn main(): i32 {{\n  let acc = 0: u64\n{calls}\n  if acc > 0 0 else 1\n}}\n")
    out = out_dir / "stress100.k1"
    out.write_text("\n".join(parts))
    print(f"wrote {out} ({UNITS} units, {sum(p.count(chr(10)) for p in parts)} lines)")


main()
