ARG CROSS_BASE_IMAGE=missing-base-image
FROM $CROSS_BASE_IMAGE AS llvm-builder

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    git cmake build-essential clang libc++-dev libc++abi-dev python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /llvm-build
COPY llvm/get_llvm.sh .
RUN chmod +x get_llvm.sh
RUN ./get_llvm.sh

# Stage 2
FROM $CROSS_BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    libc++-dev libc++abi-dev \   
    && rm -rf /var/lib/apt/lists/*

# Just copy the compiled output, not the source or build dirs
COPY --from=llvm-builder /llvm-build/install-llvm /opt/llvm

ENV PATH="/opt/llvm/bin:${PATH}"
ENV LLVM_SYS_221_PREFIX="/opt/llvm"
